# Change these first
owner: constructions-incongrues # Your GitHub organization or username, where this repository lives
repo: status-interzone # The name of this repository

sites:
  - name: amandinemeyer.com
    url: https://www.amandinemeyer.com
  - name: arrachetoiunoeil.com
    url: https://www.arrachetoiunoeil.com
  - name: brkcore.fr
    url: https://www.brkcore.fr
  - name: chipndamned.com
    url: https://www.chipndamned.com
  - name: collectionrevue.com
    url: https://www.collectionrevue.com
  - name: darlingdada.com
    url: https://www.darlingdada.com
  - name: degelite.org
    url: https://www.degelite.org
  - name: elisekobischmiana.com
    url: https://www.elisekobischmiana.com
  - name: glafouk.com
    url: https://www.glafouk.com
  - name: juliadrouhin.com
    url: https://www.juliadrouhin.com
  - name: lelaboratoire.be
    url: https://www.lelaboratoire.be
  - name: leseditionsduchevet.fr
    url: https://www.leseditionsduchevet.fr  
  - name: lesetoilesflottantes.incongru.org
    url: https://lesetoilesflottantes.incongru.org
  - name: microcontact.incongru.org
    url: https://microcontact.incongru.org
  - name: moncul.org
    url: https://www.moncul.org
  - name: nulsidecouvert.org
    url: https://www.nulsidecouvert.org
  - name: tdm.incongru.org
    url: https://tdm.incongru.org
  - name: violentnarcissus.incongru.org
    url: https://violentnarcissus.incongru.org
    
assignees:
  - trivoallan

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.interzone.network
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: dark
  name: Interzone Network
  navbar:
    - title: Constructions
      href: https://status.constructions-incongrues.net
    - title: Jean-Cloude
      href: https://status.jeancloude.club
    - title: Pantagruweb
      href: https://status.pantagruweb.club
    - title: Pastis
      href: https://pastis-hosting.net
